apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: argo
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - name: my-volume
      mountPath: /mnt/vol
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-existing-volume
