name: Publish image to Docker Hub
on:
  push
  tags:
      - 'v*'

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Extract version tag
        id: version_tag
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: build
        run: |
          docker build . -t asidhu0/toy-workflow:latest
          docker build . -t asidhu0/toy-workflow:${{ env.VERSION_TAG }} 

      - name: publish
        run: |
          docker login -u asidhu0 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push asidhu0/toy-workflow:latest
          docker push asidhu0/toy-workflow:${{ env.VERSION_TAG }}